const { nanoid } = require('nanoid');
const BANNER_PULL_COST = 10;
const BANNER_PITY_PULLS = 20;
const ACTIVE_BANNER_COUNT = 3;
const ROTATION_HOURS = 72;
const BANNERS = [
  { id: 'toji_hunt', name: 'Toji Hunt', featured: 'toji', featuredDisplay: 'Toji Fushiguro', pool: ['toji', 'maki', 'megumi', 'nanami', 'naobito', 'panda', 'inumaki', 'mai'], note: 'No Gojo or Sukuna in this banner.' },
  { id: 'shadow_monarch', name: 'Shadow Monarch', featured: 'sung jin', featuredDisplay: 'Sung Jin-Woo', pool: ['sung jin', 'igris', 'beru', 'cha hae', 'thomas andre'], note: 'Limited Solo Leveling banner.' },
  { id: 'saber_oath', name: 'Saber Oath', featured: 'saber', featuredDisplay: 'Saber', pool: ['saber', 'archer', 'emiya', 'rin tohsaka', 'lancer', 'rider'], note: 'Fate focused banner.' },
  { id: 'overlord_throne', name: 'Overlord Throne', featured: 'ainz', featuredDisplay: 'Ainz Ooal Gown', pool: ['ainz', 'albedo', 'demiurge', 'shalltear', 'cocytus'], note: 'Overlord focused banner.' },
  { id: 'hunter_oath', name: 'Hunter Oath', featured: 'kurapika', featuredDisplay: 'Kurapika', pool: ['kurapika', 'gon', 'killua', 'leorio', 'hisoka'], note: 'Hunter x Hunter focused banner.' },
  { id: 'curse_king', name: 'King of Curses', featured: 'sukuna', featuredDisplay: 'Ryomen Sukuna', pool: ['sukuna', 'uraume', 'kenjaku', 'mahito', 'jogo', 'hanami', 'dagon'], note: 'Curse-side banner.' },
  { id: 'uchiha_legend', name: 'Uchiha Legend', featured: 'itachi', featuredDisplay: 'Itachi Uchiha', pool: ['itachi', 'sasuke', 'madara', 'obito', 'shisui'], note: 'Uchiha focused banner.' },
  { id: 'strawhat_core', name: 'Straw Hat Core', featured: 'luffy', featuredDisplay: 'Monkey D. Luffy', pool: ['luffy', 'zoro', 'sanji', 'nami', 'usopp', 'robin', 'franky', 'brook', 'jinbe'], note: 'Crew banner.' }
];
function normalize(value = '') { return String(value || '').toLowerCase().replace(/[^\w\s.-]/g, '').replace(/\s+/g, ' ').trim(); }
function rotationState(now = Date.now()) { const start = new Date(process.env.BANNER_ROTATION_START || '2026-01-01T00:00:00.000Z').getTime(); const rotationMs = ROTATION_HOURS * 60 * 60 * 1000; const cycle = Math.floor(Math.max(0, now - start) / rotationMs); const endsAt = new Date(start + (cycle + 1) * rotationMs); return { cycle, endsAt }; }
function activeBanners(now = Date.now()) { const { cycle, endsAt } = rotationState(now); const rows = []; for (let x = 0; x < ACTIVE_BANNER_COUNT; x++) rows.push({ ...BANNERS[(cycle + x) % BANNERS.length], endsAt }); return rows; }
function findBanner(id) { const banners = activeBanners(); return banners.find(b => b.id === id) || banners[0]; }
function matchesBanner(character, banner) { const text = `${normalize(character.name)} ${normalize(character.anime)}`; return banner.pool.some(k => text.includes(normalize(k))); }
function pickWeighted(items, weightFn) { let total = 0; const rows = items.map(item => { const weight = Math.max(1, Math.floor(weightFn(item))); total += weight; return { item, weight }; }); let roll = Math.floor(Math.random() * total); for (const row of rows) { roll -= row.weight; if (roll <= 0) return row.item; } return rows[rows.length - 1]?.item; }
function weightFor(character, banner, pity) { const name = normalize(character.name); const featured = normalize(banner.featured); if (name.includes(featured)) return 300000 + pity * 4000; return { COMMON: 450000, RARE: 300000, EPIC: 160000, LEGENDARY: 65000, MYTHIC: 22000, DIVINE: 8000, SECRET: 1200 }[character.rarity] || 1000; }
async function getPity(prisma, userId, bannerId) { const key = `banner:${bannerId}:pity`; const row = await prisma.cooldown.findUnique({ where: { userId_key: { userId, key } } }).catch(() => null); return Number(row?.expiresAt?.getTime?.() || 0); }
async function setPity(prisma, userId, bannerId, pity) { const key = `banner:${bannerId}:pity`; await prisma.cooldown.upsert({ where: { userId_key: { userId, key } }, update: { expiresAt: new Date(Math.max(0, pity)) }, create: { userId, key, expiresAt: new Date(Math.max(0, pity)) } }).catch(() => {}); }
async function createCard(prisma, userId, character) { const updated = await prisma.character.update({ where: { id: character.id }, data: { globalPrint: { increment: 1 } } }); const shiny = Math.random() < 0.015; const power = Math.round((updated.basePower || 100) * (shiny ? 1.35 : 1) + Math.random() * 80); const card = await prisma.userCard.create({ data: { id: nanoid(12), userId, characterId: updated.id, serial: updated.globalPrint, power, shiny } }); return { card, character: updated }; }
async function rollBanner(prisma, userId, bannerId, amount = 1) { const banner = findBanner(bannerId); const safeAmount = Math.max(1, Math.min(10, Number(amount || 1))); const cost = safeAmount * BANNER_PULL_COST; const user = await prisma.user.findUnique({ where: { id: userId } }); if ((user.tokens || 0) < cost) throw new Error(`You need ${cost} tokens for ${safeAmount} banner pull(s).`); const allChars = await prisma.character.findMany({ where: { active: true }, take: 5000 }); let pool = allChars.filter(c => matchesBanner(c, banner)); if (!pool.length) pool = allChars; await prisma.user.update({ where: { id: userId }, data: { tokens: { decrement: cost } } }); let pity = await getPity(prisma, userId, banner.id); const results = []; for (let x = 0; x < safeAmount; x++) { let guaranteed = false; let character; if ((pity + 1) >= BANNER_PITY_PULLS) { character = pool.find(c => normalize(c.name).includes(normalize(banner.featured))); if (!character) character = pool.find(c => ['SECRET', 'DIVINE'].includes(c.rarity)) || pool[0]; pity = 0; guaranteed = true; } else { character = pickWeighted(pool, c => weightFor(c, banner, pity)); pity += 1; } const made = await createCard(prisma, userId, character); results.push({ ...made, guaranteed }); } await setPity(prisma, userId, banner.id, pity); return { banner, results, pity, cost }; }
module.exports = { BANNER_PULL_COST, BANNER_PITY_PULLS, ACTIVE_BANNER_COUNT, activeBanners, findBanner, getPity, rollBanner };
