// VoidRoll Reborn - Final Variant Presentation System
function normalize(v=''){return String(v||'').toLowerCase().replace(/[().\-_:/'’"]/g,' ').replace(/\s+/g,' ').trim();}
function cleanVariantName(name=''){return String(name||'').replace(/\s*\([^)]*\)\s*/g,' ').replace(/\s+/g,' ').trim();}
const PREFIXES=['Corrupted','Absolute','Voidborn','Eclipse','Abyssal','True Form','Awakened','Divine','Hollow','Bankai','Domain','Final Form','God Form','Prime','Demon King','Shadow','Limit Break','Transcendent'];
function hasVariantKeyword(t=''){const n=normalize(t);return PREFIXES.some(x=>n.includes(normalize(x)));}
function getVariantKeyword(t=''){const n=normalize(t);return PREFIXES.find(x=>n.includes(normalize(x)))||null;}
function baseNameOf(name=''){let out=cleanVariantName(name);for(const p of PREFIXES){out=out.replace(new RegExp('^'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s+','i'),'');}return out.replace(/\b(corrupted|absolute|voidborn|eclipse|abyssal|awakened|divine|hollow|bankai|domain|prime|transcendent|true form)\b/ig,' ').replace(/\s+/g,' ').trim()||cleanVariantName(name);}
const EXACT=[
{match:['corrupted aizen','corrupted sousuke aizen'],base:'Aizen',title:'Corrupted Aizen',variant:'Corrupted',eventType:'CORRUPTED_SECRET',rarity:'SECRET',element:'VOID',type:'INTELLIGENCE',role:'SUPPORT',quote:"Since when were you under the impression that I wasn't using Kyoka Suigetsu?",passiveName:"The Illusion's Peak",passiveText:'Enemy accuracy collapse, silence, and ATK reduction at battle start.',lore:'Aizen transcends reason and bends the battlefield into his own world.',color:0x7c3aed},
{match:['absolute lelouch','absolute lelouch lamperouge'],base:'Lelouch',title:'Absolute Lelouch',variant:'Absolute',eventType:'ABSOLUTE_SECRET',rarity:'SECRET',element:'DARK',type:'INTELLIGENCE',role:'CONTROL',quote:'Obey me, world.',passiveName:'Absolute Geass',passiveText:'Stuns enemies, drains energy, and lowers enemy attack.',lore:'A king whose command pierces fate itself.',color:0x8b5cf6},
{match:['corrupted lelouch','corrupted lelouch lamperouge'],base:'Lelouch',title:'Corrupted Lelouch',variant:'Corrupted',eventType:'CORRUPTED_SECRET',rarity:'SECRET',element:'VOID',type:'INTELLIGENCE',role:'CONTROL',quote:'If the world rejects my command, I will rewrite the world.',passiveName:'Corrupted Geass',passiveText:'Void Geass weakens all enemies, silences skills, and boosts team damage.',lore:'A forbidden Geass born from void corruption.',color:0x6d28d9},
{match:['corrupted makima'],base:'Makima',title:'Corrupted Makima',variant:'Corrupted',eventType:'CORRUPTED_SECRET',rarity:'SECRET',element:'VOID',type:'CONTROL',role:'CONTROL',quote:'You are mine now.',passiveName:'Control Devil Eclipse',passiveText:'Controls the strongest enemy, drains energy, and empowers allies.',lore:'A corrupted contract that turns obedience into law.',color:0xa855f7},
{match:['voidborn rimuru'],base:'Rimuru',title:'Voidborn Rimuru',variant:'Voidborn',eventType:'VOIDBORN_EVENT',rarity:'VOIDBORN',element:'VOID',type:'SUMMONER',role:'SUMMONER',quote:'I will devour everything.',passiveName:'Void Predator',passiveText:'Consumes enemy defense, heals after attacks, and summons void support.',lore:'Rimuru evolves beyond magicules into void essence.',color:0x4f46e5},
{match:['eclipse madara'],base:'Madara',title:'Eclipse Madara',variant:'Eclipse',eventType:'VOIDBORN_EVENT',rarity:'VOIDBORN',element:'SHADOW',type:'DPS',role:'DPS',quote:'Wake up to reality.',passiveName:'Eclipse Susanoo',passiveText:'Boosts AoE damage, counters attacks, and burns weakened enemies.',lore:'The battlefield becomes an eclipse under his Susanoo.',color:0x581c87},
{match:['abyssal ichigo'],base:'Ichigo',title:'Abyssal Ichigo',variant:'Abyssal',eventType:'VOIDBORN_EVENT',rarity:'VOIDBORN',element:'SOUL',type:'DPS',role:'DPS',quote:'My soul will cut through the abyss.',passiveName:'Abyssal Bankai',passiveText:'High crit, lifesteal, boss damage, and bonus energy gain.',lore:'A soul-pressure form that answers the abyss.',color:0x4338ca},
{match:['true form sukuna'],base:'Sukuna',title:'True Form Sukuna',variant:'True Form',eventType:'SECRET_FORM',rarity:'SECRET',element:'CURSED',type:'DPS',role:'DPS',quote:'Know your place.',passiveName:'Malevolent True Shrine',passiveText:'Bleeds enemies, executes low HP targets, and deals extreme boss damage.',lore:'The old king of curses restored to true terror.',color:0xdc2626},
{match:['awakened naruto'],base:'Naruto',title:'Awakened Naruto',variant:'Awakened',eventType:'VOIDBORN_EVENT',rarity:'VOIDBORN',element:'LIGHT',type:'DPS',role:'DPS',quote:'I never go back on my word.',passiveName:'Awakened Kurama Will',passiveText:'Team damage, healing, counters, and fast ultimate energy gain.',lore:'A light variant born from unbreakable will.',color:0xf59e0b}
];
const GEN={corrupted:['Corrupted','CORRUPTED_SECRET','SECRET','VOID','CORRUPTION','CONTROL',0x7c3aed,'Corrupted Aura','Reduces enemy attack, drains energy, and boosts damage against debuffed enemies.','The void has rewritten this soul.'],absolute:['Absolute','ABSOLUTE_SECRET','SECRET','DARK','INTELLIGENCE','CONTROL',0x8b5cf6,'Absolute Command','Controls enemies, lowers enemy attack, and increases team damage.','One command is enough.'],voidborn:['Voidborn','VOIDBORN_EVENT','VOIDBORN','VOID','VOID','DPS',0x4f46e5,'Voidborn Core','Gains bonus damage, energy gain, and void resistance.','A legend has awakened from the void.'],eclipse:['Eclipse','VOIDBORN_EVENT','VOIDBORN','SHADOW','SHADOW','DPS',0x581c87,'Eclipse Aura','Adds shadow damage, counter chance, and enemy accuracy reduction.','The light disappears.'],abyssal:['Abyssal','VOIDBORN_EVENT','VOIDBORN','SOUL','ABYSS','DPS',0x4338ca,'Abyssal Pressure','Adds lifesteal, crit, and boss damage.','The abyss answers.'],awakened:['Awakened','EVENT_FORM','DIVINE','LIGHT','AWAKENED','DPS',0xf59e0b,'Awakened Will','Adds team damage, energy gain, and comeback healing.','Power awakens when resolve refuses to fall.'],divine:['Divine','DIVINE_EVENT','DIVINE','LIGHT','DIVINE','SUPPORT',0xffffff,'Divine Authority','Starts with shield, buffs team damage, and improves healing.','A divine presence enters the battlefield.']};
function exactProfileFor(c={}){const n=normalize(c.name);return EXACT.find(v=>v.match.some(m=>n===normalize(m)||n.includes(normalize(m))))||null;}
function getVariantProfile(c={}){const ex=exactProfileFor(c);if(ex)return {...ex,isVariant:true,baseName:ex.base};const kw=getVariantKeyword(c.name);if(!kw)return {isVariant:false,baseName:baseNameOf(c.name),title:cleanVariantName(c.name),variant:'Base',eventType:'BASE',rarity:c.rarity,element:c.element,role:c.role,type:c.type||c.role,color:0x5865f2};const g=GEN[normalize(kw).split(' ')[0]]||GEN.voidborn;return {isVariant:true,baseName:baseNameOf(c.name),title:cleanVariantName(c.name),variant:g[0],eventType:g[1],rarity:c.rarity||g[2],element:g[3],type:g[4],role:g[5],color:g[6],passiveName:g[7],passiveText:g[8],quote:g[9],lore:'A special event variant with unique presentation.'};}
function isSpecialVariant(c={}){return !!getVariantProfile(c).isVariant;}
function queryHasVariant(q=''){return hasVariantKeyword(q);}
function searchScoreAdjustment(c={},query=''){const q=normalize(query);const p=getVariantProfile(c);if(!p.isVariant)return queryHasVariant(q)?-5000:2500;const v=normalize(p.variant),t=normalize(p.title),b=normalize(p.baseName);let s=0;if(t===q)s+=2000000;if(q.includes(v)&&t.includes(q))s+=1000000;if(q.includes(v)&&t.includes(v))s+=500000;if(q===b&&!queryHasVariant(q))s-=600000;if(!queryHasVariant(q))s-=350000;return s;}
function variantFamilyKey(c={}){return normalize(baseNameOf(c.name));}
function revealData(c={}){const p=getVariantProfile(c);const rarity=p.rarity||c.rarity||'SECRET';const title=p.title||cleanVariantName(c.name);return {...p,title,rarity,anime:c.anime||'Unknown',power:c.basePower||c.power||0,imageUrl:c.imageUrl,color:p.color||(rarity==='SECRET'?0x7c3aed:0x4f46e5),steps:[{label:'1. DARKNESS',title:'🌑 Darkness',text:'A dark aura begins to gather...'},{label:'2. DISTORTION',title:'🕳️ Distortion',text:`The silhouette of **${title}** tears through reality.`},{label:'3. QUOTE APPEARS',title:'💬 Quote Appears',text:`“${p.quote||'A legend has awakened from the void.'}”`},{label:'4. SECRET FLASH',title:rarity==='SECRET'?'🌠 SECRET FLASH':'🌌 VOID FLASH',text:`**${rarity}** energy erupts across the banner.`},{label:'5. CHARACTER REVEAL',title:`${rarity==='SECRET'?'🌠':'🌌'} ${title}`,text:`**${title}** has been revealed.`}]};}
function buildRevealEmbeds(EmbedBuilder,c={},extra=''){const d=revealData(c);return d.steps.map((st,i)=>{const fin=i===d.steps.length-1;const e=new EmbedBuilder().setTitle(st.title).setDescription([st.text,'',fin?`Rarity: **${d.rarity}**`:'',fin?`Element: **${d.element||c.element||'VOID'}**`:'',fin?`Type: **${d.type||d.role||'SPECIAL'}**`:'',fin?`Role: **${d.role||c.role||'DPS'}**`:'',fin&&d.passiveName?`Passive: **${d.passiveName}** — ${d.passiveText}`:'',fin&&d.lore?`Lore: ${d.lore}`:'',fin&&extra?extra:''].filter(Boolean).join('\n')).setColor(d.color||0x7c3aed).setFooter({text:st.label});if(fin&&d.imageUrl)e.setImage(d.imageUrl);return e;});}
function groupVariants(chars=[]){const m=new Map();for(const c of chars){const k=variantFamilyKey(c);if(!m.has(k))m.set(k,[]);m.get(k).push({character:c,profile:getVariantProfile(c)});}return m;}
module.exports={normalize,baseNameOf,getVariantProfile,isSpecialVariant,queryHasVariant,searchScoreAdjustment,variantFamilyKey,revealData,buildRevealEmbeds,groupVariants};
